"""empty message

Revision ID: d77f0cf4a098
Revises: 115bead9b569
Create Date: 2024-12-09 19:42:13.935858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77f0cf4a098'
down_revision: Union[str, None] = '115bead9b569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
